# Site settings
title: Kaurin's Paste Dump
email: kaurin@users.noreply.github.com
description: > # this means to ignore newlines until "baseurl:"
       Welcome to my paste dump!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://kaurin.github.io" # the base hostname & protocol for your site
twitter_username: kaurin011
github_username:  kaurin

# Build settings
markdown: kramdown

# Milos
timezone: Europe/Dublin
encoding: utf-8

# Github override
highlighter: pygments
